apiVersion: batch/v1
kind: CronJob
metadata:
  name: travelonna-recommendation-batch
  labels:
    app: travelonna-recommendation-batch
spec:
  # 매일 새벽 2시에 전체 배치 실행
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-runner
            image: travelonna/recommendation-service:latest  # 동일한 이미지 사용
            command: ["python", "batch_runner.py", "--mode", "full"]
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: CONFIG_DIR
              value: "/app/config"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: models-volume
              mountPath: /app/models
              readOnly: true
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "500m"
          volumes:
          - name: config-volume
            configMap:
              name: travelonna-config
          - name: models-volume
            persistentVolumeClaim:
              claimName: travelonna-models-pvc
          restartPolicy: OnFailure
          backoffLimit: 3
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

---
apiVersion: batch/v1
kind: CronJob  
metadata:
  name: travelonna-recommendation-incremental
  labels:
    app: travelonna-recommendation-incremental
spec:
  # 6시간마다 증분 배치 실행
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-runner
            image: travelonna/recommendation-service:latest
            command: ["python", "batch_runner.py", "--mode", "incremental"]
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker" 
            - name: CONFIG_DIR
              value: "/app/config"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: models-volume
              mountPath: /app/models
              readOnly: true
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "300m"
          volumes:
          - name: config-volume
            configMap:
              name: travelonna-config
          - name: models-volume
            persistentVolumeClaim:
              claimName: travelonna-models-pvc
          restartPolicy: OnFailure
          backoffLimit: 2
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1 